# Generated by Django 4.2.5 on 2023-10-01 22:58

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawlspace', models.TextField(null=True)),
                ('access', models.TextField(null=True)),
                ('foundation', models.TextField(null=True)),
                ('floor', models.TextField(null=True)),
                ('seismic_bolts', models.TextField(null=True)),
                ('drainage', models.TextField(null=True)),
                ('ventilation', models.TextField(null=True)),
                ('girders_beams', models.TextField(null=True)),
                ('joists', models.TextField(null=True)),
                ('subfloor', models.TextField(null=True)),
                ('insulation', models.TextField(null=True)),
                ('vapor_barriers', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiningRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dining_room', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricalCoolingSystems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Exterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chimney', models.TextField(null=True)),
                ('gutters', models.TextField(null=True)),
                ('siding', models.TextField(null=True)),
                ('trim', models.TextField(null=True)),
                ('soffit', models.TextField(null=True)),
                ('fascia', models.TextField(null=True)),
                ('flashing', models.TextField(null=True)),
                ('caulking', models.TextField(null=True)),
                ('windows', models.TextField(null=True)),
                ('storm_windows', models.TextField(null=True)),
                ('slab_on_foundation', models.TextField(null=True)),
                ('service_entry', models.TextField(null=True)),
                ('wall_construction', models.TextField(null=True)),
                ('exterior_doors', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GarageCarport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(null=True)),
                ('automatic_opener', models.TextField(null=True)),
                ('safety_reverse', models.TextField(null=True)),
                ('roofing', models.TextField(null=True)),
                ('gutters', models.TextField(null=True)),
                ('siding', models.TextField(null=True)),
                ('trim', models.TextField(null=True)),
                ('floor', models.TextField(null=True)),
                ('sillplate', models.TextField(null=True)),
                ('overhead_doors', models.TextField(null=True)),
                ('service_door', models.TextField(null=True)),
                ('electrical', models.TextField(null=True)),
                ('walls_ceiling', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_walks', models.TextField(null=True)),
                ('drive_parking', models.TextField(null=True)),
                ('stoop_steps', models.TextField(null=True)),
                ('patio', models.TextField(null=True)),
                ('deck_balcony', models.TextField(null=True)),
                ('covers', models.TextField(null=True)),
                ('fence_wall', models.TextField(null=True)),
                ('landscaping', models.TextField(null=True)),
                ('retaining_wall', models.TextField(null=True)),
                ('hose_bibs', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_systems', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plumbing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_service', models.TextField(null=True)),
                ('fuel_shutoff', models.TextField(null=True)),
                ('well_pump', models.TextField(null=True)),
                ('sanitary_pump', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportDetails',
            fields=[
                ('report_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('r_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('customer_fname', models.CharField(max_length=25)),
                ('customer_lname', models.CharField(max_length=25)),
                ('bedroom_count', models.SmallIntegerField(default=0)),
                ('bathroom_count', models.SmallIntegerField(default=0)),
                ('garage_type', models.CharField(max_length=10)),
                ('basement_type', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Boiler',
            fields=[
                ('heatingsystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.heatingsystem')),
                ('boiler_unit', models.TextField(null=True)),
            ],
            bases=('core.heatingsystem',),
        ),
        migrations.CreateModel(
            name='EvaporatorCoil',
            fields=[
                ('electricalcoolingsystems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.electricalcoolingsystems')),
                ('evap_coil', models.TextField(null=True)),
            ],
            bases=('core.electricalcoolingsystems',),
        ),
        migrations.CreateModel(
            name='ExteriorACUnit',
            fields=[
                ('exterior_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.exterior')),
                ('exterior_ac', models.TextField(null=True)),
            ],
            bases=('core.exterior',),
        ),
        migrations.CreateModel(
            name='Furnace',
            fields=[
                ('heatingsystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.heatingsystem')),
                ('furnace_unit', models.TextField(null=True)),
            ],
            bases=('core.heatingsystem',),
        ),
        migrations.CreateModel(
            name='MainPanel',
            fields=[
                ('electricalcoolingsystems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.electricalcoolingsystems')),
                ('main_panel', models.TextField(null=True)),
            ],
            bases=('core.electricalcoolingsystems',),
        ),
        migrations.CreateModel(
            name='SubPanel',
            fields=[
                ('electricalcoolingsystems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.electricalcoolingsystems')),
                ('sub_panel', models.TextField(null=True)),
            ],
            bases=('core.electricalcoolingsystems',),
        ),
        migrations.CreateModel(
            name='WaterHeater',
            fields=[
                ('plumbing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.plumbing')),
                ('water_heater', models.TextField(null=True)),
            ],
            bases=('core.plumbing',),
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_not_operating', models.TextField(null=True)),
                ('major_concerns', models.TextField(null=True)),
                ('safety_hazards', models.TextField(null=True)),
                ('further_review', models.TextField(null=True)),
                ('monitor', models.TextField(null=True)),
                ('general_maintenance', models.TextField(null=True)),
                ('needing_repair', models.TextField(null=True)),
                ('report_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Roof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.TextField(null=True)),
                ('style', models.TextField(null=True)),
                ('ventilation', models.TextField(null=True)),
                ('flashing', models.TextField(null=True)),
                ('valleys', models.TextField(null=True)),
                ('condition', models.TextField(null=True)),
                ('skylights', models.TextField(null=True)),
                ('plumbing_vents', models.TextField(null=True)),
                ('report_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=75)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('inspector_fname', models.CharField(max_length=25)),
                ('inspector_lname', models.CharField(max_length=25)),
                ('client_fname', models.CharField(max_length=25)),
                ('client_lname', models.CharField(max_length=25)),
                ('payment_type', models.CharField(max_length=15)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('report_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails')),
            ],
        ),
        migrations.AddField(
            model_name='plumbing',
            name='report_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails'),
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grounds_photos', models.ImageField(null=True, upload_to=core.models.logo_image_file_path)),
                ('roof_photos', models.ImageField(null=True, upload_to=core.models.logo_image_file_path)),
                ('exterior_photos', models.ImageField(null=True, upload_to=core.models.logo_image_file_path)),
                ('garage_photos', models.ImageField(null=True, upload_to=core.models.logo_image_file_path)),
                ('kitchen_photos', models.ImageField(null=True, upload_to=core.models.logo_image_file_path)),
                ('laundry_photos', models.ImageField(null=True, upload_to=core.models.logo_image_file_path)),
                ('bathroom_photos', models.ImageField(null=True, upload_to=core.models.logo_image_file_path)),
                ('bedrooms_photos', models.ImageField(null=True, upload_to=core.models.logo_image_file_path)),
                ('interior_photos', models.ImageField(null=True, upload_to=core.models.logo_image_file_path)),
                ('basement_photos', models.ImageField(null=True, upload_to=core.models.logo_image_file_path)),
                ('crawl_photos', models.ImageField(null=True, upload_to=core.models.logo_image_file_path)),
                ('plumbing_photos', models.ImageField(null=True, upload_to=core.models.logo_image_file_path)),
                ('heating_photos', models.ImageField(null=True, upload_to=core.models.logo_image_file_path)),
                ('living_room_photos', models.ImageField(null=True, upload_to=core.models.logo_image_file_path)),
                ('dining_room_photos', models.ImageField(null=True, upload_to=core.models.logo_image_file_path)),
                ('report_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.TextField()),
                ('state_of_occupancy', models.CharField(max_length=15)),
                ('weather', models.CharField(max_length=15)),
                ('recent_rain', models.CharField(max_length=10)),
                ('ground_cover', models.CharField(max_length=15)),
                ('approx_age', models.CharField(max_length=10)),
                ('report_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails')),
            ],
        ),
        migrations.CreateModel(
            name='LivingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_room', models.TextField(null=True)),
                ('report_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laundry', models.TextField(null=True)),
                ('report_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countertops', models.TextField(null=True)),
                ('cabinets', models.TextField(null=True)),
                ('plumbing', models.TextField(null=True)),
                ('walls_ceiling', models.TextField(null=True)),
                ('heating_cooling', models.TextField(null=True)),
                ('floor', models.TextField(null=True)),
                ('appliances', models.TextField(null=True)),
                ('report_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fireplace', models.TextField(null=True)),
                ('stairs_steps', models.TextField(null=True)),
                ('smoke_carbon_det', models.TextField(null=True)),
                ('attic', models.TextField(null=True)),
                ('report_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bathroom')),
                ('crawlspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.crawlspace')),
                ('dining_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.diningroom')),
                ('electrical_cooling', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.electricalcoolingsystems')),
                ('exterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.exterior')),
                ('garage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.garagecarport')),
                ('grounds', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.grounds')),
                ('heatingsystem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.heatingsystem')),
                ('kitchen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.kitchen')),
                ('laundry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.laundry')),
                ('living_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.livingroom')),
                ('overview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.overview')),
                ('photos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.photos')),
                ('plumbing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plumbing')),
                ('receipt_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.receiptinvoice')),
                ('report_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails')),
                ('roof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.roof')),
                ('summary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.summary')),
            ],
        ),
        migrations.AddField(
            model_name='heatingsystem',
            name='report_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails'),
        ),
        migrations.AddField(
            model_name='grounds',
            name='report_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails'),
        ),
        migrations.AddField(
            model_name='garagecarport',
            name='report_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails'),
        ),
        migrations.AddField(
            model_name='exterior',
            name='report_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails'),
        ),
        migrations.AddField(
            model_name='electricalcoolingsystems',
            name='report_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails'),
        ),
        migrations.AddField(
            model_name='diningroom',
            name='report_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails'),
        ),
        migrations.AddField(
            model_name='crawlspace',
            name='report_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails'),
        ),
        migrations.CreateModel(
            name='Bedrooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedroom', models.TextField(null=True)),
                ('report_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails')),
            ],
        ),
        migrations.AddField(
            model_name='bathroom',
            name='report_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails'),
        ),
        migrations.CreateModel(
            name='Basement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stairs', models.TextField(null=True)),
                ('foundation', models.TextField(null=True)),
                ('floor', models.TextField(null=True)),
                ('seismic_bolts', models.TextField(null=True)),
                ('drainage', models.TextField(null=True)),
                ('girders_beams', models.TextField(null=True)),
                ('columns', models.TextField(null=True)),
                ('joists', models.TextField(null=True)),
                ('subfloor', models.TextField(null=True)),
                ('report_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportdetails')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('invited_user_count', models.SmallIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
