# Generated by Django 4.2.5 on 2023-09-25 18:15

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('phone_number', models.PositiveIntegerField(default=0)),
                ('license', models.CharField(default=0, max_length=50)),
                ('signature', models.ImageField(null=True, upload_to=core.models.signature_image_file_path)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.CharField(max_length=30)),
                ('owner_email', models.CharField(max_length=75)),
                ('company_name', models.CharField(max_length=75)),
                ('company_addr', models.CharField(max_length=255)),
                ('phone_number', models.PositiveIntegerField(default=0)),
                ('logo', models.ImageField(null=True, upload_to=core.models.logo_image_file_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportDetails',
            fields=[
                ('report_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('r_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('customer_fname', models.CharField(max_length=25)),
                ('customer_lname', models.CharField(max_length=25)),
                ('bedroom_count', models.SmallIntegerField(default=0)),
                ('bathroom_count', models.SmallIntegerField(default=0)),
                ('garage_type', models.CharField(max_length=10)),
                ('basement', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
