# Generated by Django 4.2.5 on 2023-09-24 01:31

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.CharField(max_length=30)),
                ('owner_email', models.CharField(max_length=75)),
                ('company_name', models.CharField(max_length=75)),
                ('company_addr', models.CharField(max_length=255)),
                ('phone_number', models.PositiveIntegerField(default=0)),
                ('logo', models.ImageField(null=True, upload_to=core.models.logo_image_file_path)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='company_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='license',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(null=True, upload_to=core.models.signature_image_file_path),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
