# Generated by Django 4.2.5 on 2023-09-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_user_company_id_user_license_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_id',
        ),
    ]
