# Generated by Django 4.2.5 on 2023-10-02 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inspectionreport_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdetails',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
